/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.18).
 * https://github.com/swagger-api/swagger-codegen Do not edit the class manually.
 */
package com.zl.way.mp.api;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.zl.way.mp.api.model.ApiResponseMessage;
import com.zl.way.mp.api.model.WayAuditArticlePostReq;
import com.zl.way.mp.api.model.WayQueryArticlePost;
import com.zl.way.mp.api.model.WayQueryArticlePostResp;

@RequestMapping(value = "")
public interface WayArticlePostApi {

    @RequestMapping(value = "/mp/article/audit/{postId}", produces = {"application/json"},
        consumes = {"application/json"}, method = RequestMethod.PUT)
    ResponseEntity<ApiResponseMessage> auditArticle(@Valid @RequestBody WayAuditArticlePostReq body,
        @PathVariable("postId") Long postId,
        @RequestHeader(value = "X-userLoginId", required = true) Long xUserLoginId);

    @RequestMapping(value = "/mp/article/{postId}", produces = {"application/json"}, method = RequestMethod.DELETE)
    ResponseEntity<ApiResponseMessage> deleteArticle(@PathVariable("postId") Long postId,
        @RequestHeader(value = "X-userLoginId", required = true) Long xUserLoginId);

    @RequestMapping(value = "/mp/article/{postId}", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<WayQueryArticlePost> getArticle(@PathVariable("postId") Long postId,
        @RequestHeader(value = "X-userLoginId", required = true) Long xUserLoginId);

    @RequestMapping(value = "/mp/article", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<WayQueryArticlePostResp> queryArticles(
        @NotNull @Valid @RequestParam(value = "page", required = true, defaultValue = "1") Integer page,
        @NotNull @Valid @RequestParam(value = "pageSize", required = true, defaultValue = "10") Integer pageSize,
        @Valid @RequestParam(value = "keywords", required = false) String keywords,
        @Valid @RequestParam(value = "postId", required = false) Long postId);

}
