package com.zl.way.shop.mapper;

import com.zl.way.shop.model.WayShopCateLeaf;
import org.springframework.stereotype.Repository;

@Repository
public interface WayShopCateLeafMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table way_shop_cate_leaf
     *
     * @mbg.generated Fri Apr 06 16:04:02 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table way_shop_cate_leaf
     *
     * @mbg.generated Fri Apr 06 16:04:02 CST 2018
     */
    int insert(WayShopCateLeaf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table way_shop_cate_leaf
     *
     * @mbg.generated Fri Apr 06 16:04:02 CST 2018
     */
    int insertSelective(WayShopCateLeaf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table way_shop_cate_leaf
     *
     * @mbg.generated Fri Apr 06 16:04:02 CST 2018
     */
    WayShopCateLeaf selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table way_shop_cate_leaf
     *
     * @mbg.generated Fri Apr 06 16:04:02 CST 2018
     */
    int updateByPrimaryKeySelective(WayShopCateLeaf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table way_shop_cate_leaf
     *
     * @mbg.generated Fri Apr 06 16:04:02 CST 2018
     */
    int updateByPrimaryKey(WayShopCateLeaf record);
}