package com.zl.way.shop.mapper;

import com.zl.way.shop.model.WayShopCateRoot;
import org.springframework.stereotype.Repository;

@Repository
public interface WayShopCateRootMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table way_shop_cate_root
     *
     * @mbg.generated Fri Apr 06 16:04:02 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table way_shop_cate_root
     *
     * @mbg.generated Fri Apr 06 16:04:02 CST 2018
     */
    int insert(WayShopCateRoot record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table way_shop_cate_root
     *
     * @mbg.generated Fri Apr 06 16:04:02 CST 2018
     */
    int insertSelective(WayShopCateRoot record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table way_shop_cate_root
     *
     * @mbg.generated Fri Apr 06 16:04:02 CST 2018
     */
    WayShopCateRoot selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table way_shop_cate_root
     *
     * @mbg.generated Fri Apr 06 16:04:02 CST 2018
     */
    int updateByPrimaryKeySelective(WayShopCateRoot record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table way_shop_cate_root
     *
     * @mbg.generated Fri Apr 06 16:04:02 CST 2018
     */
    int updateByPrimaryKey(WayShopCateRoot record);
}