spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  profiles:
    active: development
    include: amap, jpush

  resources:
    add-mappings: false

  mvc:
    favicon:
      enabled: false

  pid:
    file: /apps/pid/api.pid

server:
  port: 8080
  servlet:
    context-path:
  tomcat:
    uri-encoding: UTF-8
  error:
    whitelabel:
      enabled: false

mybatis:
  mapper-locations: classpath:mappers/h5app/*Mapper.xml,classpath:mappers/sp/*Mapper.xml,classpath:mappers/mp/*Mapper.xml,classpath:mappers/push/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

custom:
  discount:
    imageUrl: http://h5.jicu.vip/images/%s.jpg
  user:
    agreementsUrl: http://h5.jicu.vip/user_agreements.html