package com.zl.way.user.mapper;

import com.zl.way.user.model.UserLogin;
import com.zl.way.user.model.UserLoginQueryCondition;
import org.apache.ibatis.annotations.Param;

public interface UserLoginMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_login
     *
     * @mbg.generated Sat Jun 23 14:42:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_login
     *
     * @mbg.generated Sat Jun 23 14:42:03 CST 2018
     */
    int insert(UserLogin record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_login
     *
     * @mbg.generated Sat Jun 23 14:42:03 CST 2018
     */
    int insertSelective(UserLogin record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_login
     *
     * @mbg.generated Sat Jun 23 14:42:03 CST 2018
     */
    UserLogin selectByPrimaryKey(@Param("condition") UserLoginQueryCondition userLoginQueryCondition);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_login
     *
     * @mbg.generated Sat Jun 23 14:42:03 CST 2018
     */
    int updateByPrimaryKeySelective(UserLogin record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_login
     *
     * @mbg.generated Sat Jun 23 14:42:03 CST 2018
     */
    int updateByPrimaryKey(UserLogin record);
}