package com.zl.way.user.mapper;

import com.zl.way.user.model.UserProfile;
import com.zl.way.user.model.UserProfileQueryCondition;
import org.apache.ibatis.annotations.Param;

public interface UserProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Sat Jun 23 14:42:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Sat Jun 23 14:42:03 CST 2018
     */
    int insert(UserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Sat Jun 23 14:42:03 CST 2018
     */
    int insertSelective(UserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Sat Jun 23 14:42:03 CST 2018
     */
    UserProfile selectByPrimaryKey(@Param("condition") UserProfileQueryCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Sat Jun 23 14:42:03 CST 2018
     */
    int updateByPrimaryKeySelective(UserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Sat Jun 23 14:42:03 CST 2018
     */
    int updateByPrimaryKey(UserProfile record);
}