package com.zl.way.shop.api.model;

import com.zl.way.commodity.model.WayCommodity;

import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table way_shop
 *
 * @mbg.generated do_not_delete_during_merge Fri Apr 06 16:07:59 CST 2018
 */
public class WayShopResponse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_shop.id
     *
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    private Long id;

    /**
     * Database Column Remarks:
     * 商家名称
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_shop.shop_name
     *
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    private String shopName;

    /**
     * Database Column Remarks:
     * 商家地址
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_shop.shop_address
     *
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    private String shopAddress;

    /**
     * Database Column Remarks:
     * 商家电话
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_shop.shop_tel
     *
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    private String shopTel;

    /**
     * Database Column Remarks:
     * 商家营业时间1
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_shop.shop_business_time1
     *
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    private String shopBusinessTime1;

    /**
     * Database Column Remarks:
     * 商家营业时间2
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_shop.shop_business_time2
     *
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    private String shopBusinessTime2;

    /**
     * Database Column Remarks:
     * 商家分类末级id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_shop.shop_cate_leaf_id
     *
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    private String shopCateLeafName;

    /**
     * Database Column Remarks:
     * 商家信息
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_shop.shop_info
     *
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    private String shopInfo;

    private String shopLogoUrl;

    private String shopDistance;

    private List<WayCommodity> commodityList;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getShopName() {
        return shopName;
    }

    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    public String getShopAddress() {
        return shopAddress;
    }

    public void setShopAddress(String shopAddress) {
        this.shopAddress = shopAddress == null ? null : shopAddress.trim();
    }

    public String getShopTel() {
        return shopTel;
    }

    public void setShopTel(String shopTel) {
        this.shopTel = shopTel == null ? null : shopTel.trim();
    }

    public String getShopBusinessTime1() {
        return shopBusinessTime1;
    }

    public void setShopBusinessTime1(String shopBusinessTime1) {
        this.shopBusinessTime1 = shopBusinessTime1 == null ? null : shopBusinessTime1.trim();
    }

    public String getShopBusinessTime2() {
        return shopBusinessTime2;
    }

    public void setShopBusinessTime2(String shopBusinessTime2) {
        this.shopBusinessTime2 = shopBusinessTime2 == null ? null : shopBusinessTime2.trim();
    }

    public String getShopCateLeafName() {
        return shopCateLeafName;
    }

    public void setShopCateLeafName(String shopCateLeafName) {
        this.shopCateLeafName = shopCateLeafName;
    }

    public String getShopInfo() {
        return shopInfo;
    }

    public void setShopInfo(String shopInfo) {
        this.shopInfo = shopInfo == null ? null : shopInfo.trim();
    }

    public List<WayCommodity> getCommodityList() {
        return commodityList;
    }

    public void setCommodityList(List<WayCommodity> commodityList) {
        this.commodityList = commodityList;
    }

    public String getShopDistance() {
        return shopDistance;
    }

    public void setShopDistance(String shopDistance) {
        this.shopDistance = shopDistance;
    }

    public String getShopLogoUrl() {
        return shopLogoUrl;
    }

    public void setShopLogoUrl(String shopLogoUrl) {
        this.shopLogoUrl = shopLogoUrl;
    }
}