package com.zl.way.commodity.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Repository;

import com.zl.way.commodity.mapper.model.WayCommodityCondition;
import com.zl.way.commodity.model.WayCommodity;

@Repository
public interface WayCommodityMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table way_commodity
     *
     * @mbg.generated Fri Jun 08 15:06:59 CST 2018
     */
    int insert(WayCommodity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table way_commodity
     *
     * @mbg.generated Fri Jun 08 15:06:59 CST 2018
     */
    int insertSelective(WayCommodity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table way_commodity
     *
     * @mbg.generated Fri Jun 08 15:06:59 CST 2018
     */
    WayCommodity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table way_commodity
     *
     * @mbg.generated Fri Jun 08 15:06:59 CST 2018
     */
    int updateByPrimaryKeySelective(WayCommodity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table way_commodity
     *
     * @mbg.generated Fri Jun 08 15:06:59 CST 2018
     */
    int updateByPrimaryKey(WayCommodity record);

    List<WayCommodity> selectByCondition(@Param("condition") WayCommodityCondition condition,
        @Param("pageable") Pageable pageable);
}