package com.zl.way.commodity.mapper;

import com.zl.way.commodity.mapper.model.WayCommodityQueryCondition;
import com.zl.way.commodity.model.WayCommodity;
import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.Pageable;

import java.util.List;

public interface WayCommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table way_commodity
     *
     * @mbg.generated Fri Jun 08 15:06:59 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table way_commodity
     *
     * @mbg.generated Fri Jun 08 15:06:59 CST 2018
     */
    int insert(WayCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table way_commodity
     *
     * @mbg.generated Fri Jun 08 15:06:59 CST 2018
     */
    int insertSelective(WayCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table way_commodity
     *
     * @mbg.generated Fri Jun 08 15:06:59 CST 2018
     */
    WayCommodity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table way_commodity
     *
     * @mbg.generated Fri Jun 08 15:06:59 CST 2018
     */
    int updateByPrimaryKeySelective(WayCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table way_commodity
     *
     * @mbg.generated Fri Jun 08 15:06:59 CST 2018
     */
    int updateByPrimaryKey(WayCommodity record);

    List<WayCommodity> selectByCondition(@Param("condition") WayCommodityQueryCondition condition, @Param("pageable") Pageable pageable);
}