package com.zl.way.discount.model;

import java.util.Date;

public class WayDiscountReal {
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column way_discount_real.id
	 *
	 * @mbg.generated Fri Jul 06 17:36:56 CST 2018
	 */
	private Long id;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column way_discount_real.user_login_id
	 *
	 * @mbg.generated Fri Jul 06 17:36:56 CST 2018
	 */
	private Long userLoginId;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column way_discount_real.discount_id
	 *
	 * @mbg.generated Fri Jul 06 17:36:56 CST 2018
	 */
	private Long discountId;

	private Byte realType;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column way_discount_real.create_time
	 *
	 * @mbg.generated Fri Jul 06 17:36:56 CST 2018
	 */
	private Date createTime;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column way_discount_real.update_time
	 *
	 * @mbg.generated Fri Jul 06 17:36:56 CST 2018
	 */
	private Date updateTime;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column way_discount_real.is_deleted
	 *
	 * @mbg.generated Fri Jul 06 17:36:56 CST 2018
	 */
	private Byte isDeleted;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column way_discount_real.id
	 *
	 * @return the value of way_discount_real.id
	 *
	 * @mbg.generated Fri Jul 06 17:36:56 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column way_discount_real.id
	 *
	 * @param id the value for way_discount_real.id
	 *
	 * @mbg.generated Fri Jul 06 17:36:56 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column way_discount_real.user_login_id
	 *
	 * @return the value of way_discount_real.user_login_id
	 *
	 * @mbg.generated Fri Jul 06 17:36:56 CST 2018
	 */
	public Long getUserLoginId() {
		return userLoginId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column way_discount_real.user_login_id
	 *
	 * @param userLoginId the value for way_discount_real.user_login_id
	 *
	 * @mbg.generated Fri Jul 06 17:36:56 CST 2018
	 */
	public void setUserLoginId(Long userLoginId) {
		this.userLoginId = userLoginId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column way_discount_real.discount_id
	 *
	 * @return the value of way_discount_real.discount_id
	 *
	 * @mbg.generated Fri Jul 06 17:36:56 CST 2018
	 */
	public Long getDiscountId() {
		return discountId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column way_discount_real.discount_id
	 *
	 * @param discountId the value for way_discount_real.discount_id
	 *
	 * @mbg.generated Fri Jul 06 17:36:56 CST 2018
	 */
	public void setDiscountId(Long discountId) {
		this.discountId = discountId;
	}

	public Byte getRealType() {
		return realType;
	}

	public void setRealType(Byte realType) {
		this.realType = realType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column way_discount_real.create_time
	 *
	 * @return the value of way_discount_real.create_time
	 *
	 * @mbg.generated Fri Jul 06 17:36:56 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column way_discount_real.create_time
	 *
	 * @param createTime the value for way_discount_real.create_time
	 *
	 * @mbg.generated Fri Jul 06 17:36:56 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column way_discount_real.update_time
	 *
	 * @return the value of way_discount_real.update_time
	 *
	 * @mbg.generated Fri Jul 06 17:36:56 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column way_discount_real.update_time
	 *
	 * @param updateTime the value for way_discount_real.update_time
	 *
	 * @mbg.generated Fri Jul 06 17:36:56 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column way_discount_real.is_deleted
	 *
	 * @return the value of way_discount_real.is_deleted
	 *
	 * @mbg.generated Fri Jul 06 17:36:56 CST 2018
	 */
	public Byte getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column way_discount_real.is_deleted
	 *
	 * @param isDeleted the value for way_discount_real.is_deleted
	 *
	 * @mbg.generated Fri Jul 06 17:36:56 CST 2018
	 */
	public void setIsDeleted(Byte isDeleted) {
		this.isDeleted = isDeleted;
	}
}