package com.zl.way.discount.mapper;

import com.zl.way.discount.model.WayDiscount;
import com.zl.way.discount.model.WayDiscountQueryCondition;
import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.Pageable;

import java.util.List;

public interface WayDiscountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table way_discount
     *
     * @mbg.generated Sat Jun 23 14:42:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table way_discount
     *
     * @mbg.generated Sat Jun 23 14:42:03 CST 2018
     */
    int insert(WayDiscount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table way_discount
     *
     * @mbg.generated Sat Jun 23 14:42:03 CST 2018
     */
    int insertSelective(WayDiscount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table way_discount
     *
     * @mbg.generated Sat Jun 23 14:42:03 CST 2018
     */
    WayDiscount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table way_discount
     *
     * @mbg.generated Sat Jun 23 14:42:03 CST 2018
     */
    int updateByPrimaryKeySelective(WayDiscount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table way_discount
     *
     * @mbg.generated Sat Jun 23 14:42:03 CST 2018
     */
    int updateByPrimaryKey(WayDiscount record);

    List<WayDiscount> selectByCondition(@Param("condition") WayDiscountQueryCondition condition, @Param("pageable") Pageable pageable);
}