package com.zl.way.commodity.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table way_commodity
 *
 * @mbg.generated do_not_delete_during_merge Fri Jun 08 19:43:59 CST 2018
 */
public class WayCommodity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_commodity.id
     *
     * @mbg.generated Fri Jun 08 19:43:59 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_commodity.name
     *
     * @mbg.generated Fri Jun 08 19:43:59 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_commodity.price
     *
     * @mbg.generated Thu Jun 28 12:14:20 CST 2018
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_commodity.img_url
     *
     * @mbg.generated Thu Jun 28 19:10:46 CST 2018
     */
    private String imgUrl;

    /**
     * Database Column Remarks:
     * 商铺主键id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_commodity.shop_id
     *
     * @mbg.generated Fri Jun 08 19:43:59 CST 2018
     */
    private Long shopId;

    /**
     * Database Column Remarks:
     * 创建时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_commodity.create_time
     *
     * @mbg.generated Fri Jun 08 19:43:59 CST 2018
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     * 更新时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_commodity.update_time
     *
     * @mbg.generated Fri Jun 08 19:43:59 CST 2018
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     * 是否删除。0：未删除，1：已删除
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_commodity.is_deleted
     *
     * @mbg.generated Fri Jun 08 19:43:59 CST 2018
     */
    private Byte isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column way_commodity.id
     *
     * @return the value of way_commodity.id
     * @mbg.generated Fri Jun 08 19:43:59 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column way_commodity.id
     *
     * @param id the value for way_commodity.id
     * @mbg.generated Fri Jun 08 19:43:59 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column way_commodity.name
     *
     * @return the value of way_commodity.name
     * @mbg.generated Fri Jun 08 19:43:59 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column way_commodity.name
     *
     * @param name the value for way_commodity.name
     * @mbg.generated Fri Jun 08 19:43:59 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column way_commodity.price
     *
     * @return the value of way_commodity.price
     * @mbg.generated Thu Jun 28 12:14:20 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column way_commodity.price
     *
     * @param price the value for way_commodity.price
     * @mbg.generated Thu Jun 28 12:14:20 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column way_commodity.img_url
     *
     * @return the value of way_commodity.img_url
     * @mbg.generated Thu Jun 28 19:10:46 CST 2018
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column way_commodity.img_url
     *
     * @param imgUrl the value for way_commodity.img_url
     * @mbg.generated Thu Jun 28 19:10:46 CST 2018
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column way_commodity.shop_id
     *
     * @return the value of way_commodity.shop_id
     * @mbg.generated Fri Jun 08 19:43:59 CST 2018
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column way_commodity.shop_id
     *
     * @param shopId the value for way_commodity.shop_id
     * @mbg.generated Fri Jun 08 19:43:59 CST 2018
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column way_commodity.create_time
     *
     * @return the value of way_commodity.create_time
     * @mbg.generated Fri Jun 08 19:43:59 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column way_commodity.create_time
     *
     * @param createTime the value for way_commodity.create_time
     * @mbg.generated Fri Jun 08 19:43:59 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column way_commodity.update_time
     *
     * @return the value of way_commodity.update_time
     * @mbg.generated Fri Jun 08 19:43:59 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column way_commodity.update_time
     *
     * @param updateTime the value for way_commodity.update_time
     * @mbg.generated Fri Jun 08 19:43:59 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column way_commodity.is_deleted
     *
     * @return the value of way_commodity.is_deleted
     * @mbg.generated Fri Jun 08 19:43:59 CST 2018
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column way_commodity.is_deleted
     *
     * @param isDeleted the value for way_commodity.is_deleted
     * @mbg.generated Fri Jun 08 19:43:59 CST 2018
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}