package com.zl.way.user.model;

import java.util.Date;

public class UserLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.id
     *
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.login_tel
     *
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    private String loginTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.valid_code
     *
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    private String validCode;

    private Date validCodeExpire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.create_time
     *
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.update_time
     *
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.is_used
     *
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    private Byte isUsed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.is_deleted
     *
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.login_time
     *
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.logout_time
     *
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    private Date logoutTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.id
     *
     * @return the value of user_login.id
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.id
     *
     * @param id the value for user_login.id
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.login_tel
     *
     * @return the value of user_login.login_tel
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    public String getLoginTel() {
        return loginTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.login_tel
     *
     * @param loginTel the value for user_login.login_tel
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    public void setLoginTel(String loginTel) {
        this.loginTel = loginTel == null ? null : loginTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.valid_code
     *
     * @return the value of user_login.valid_code
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    public String getValidCode() {
        return validCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.valid_code
     *
     * @param validCode the value for user_login.valid_code
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    public void setValidCode(String validCode) {
        this.validCode = validCode == null ? null : validCode.trim();
    }

    public Date getValidCodeExpire() {
        return validCodeExpire;
    }

    public void setValidCodeExpire(Date validCodeExpire) {
        this.validCodeExpire = validCodeExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.create_time
     *
     * @return the value of user_login.create_time
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.create_time
     *
     * @param createTime the value for user_login.create_time
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.update_time
     *
     * @return the value of user_login.update_time
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.update_time
     *
     * @param updateTime the value for user_login.update_time
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.is_used
     *
     * @return the value of user_login.is_used
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    public Byte getIsUsed() {
        return isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.is_used
     *
     * @param isUsed the value for user_login.is_used
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    public void setIsUsed(Byte isUsed) {
        this.isUsed = isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.is_deleted
     *
     * @return the value of user_login.is_deleted
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.is_deleted
     *
     * @param isDeleted the value for user_login.is_deleted
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.login_time
     *
     * @return the value of user_login.login_time
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.login_time
     *
     * @param loginTime the value for user_login.login_time
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.logout_time
     *
     * @return the value of user_login.logout_time
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    public Date getLogoutTime() {
        return logoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.logout_time
     *
     * @param logoutTime the value for user_login.logout_time
     * @mbg.generated Sat Jun 23 20:32:45 CST 2018
     */
    public void setLogoutTime(Date logoutTime) {
        this.logoutTime = logoutTime;
    }
}