package com.zl.way.shop.model;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table way_shop_cate_leaf
 *
 * @mbg.generated do_not_delete_during_merge Fri Apr 06 16:07:59 CST 2018
 */
public class WayShopCateLeaf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_shop_cate_leaf.id
     *
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    private Integer id;

    /**
     * Database Column Remarks:
     * 商家分类根id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_shop_cate_leaf.shop_cate_root_id
     *
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    private Integer shopCateRootId;

    /**
     * Database Column Remarks:
     * 商家分类名称
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_shop_cate_leaf.cate_name
     *
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    private String cateName;

    /**
     * Database Column Remarks:
     * 创建时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_shop_cate_leaf.create_time
     *
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     * 更新时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_shop_cate_leaf.update_time
     *
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     * 是否删除
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column way_shop_cate_leaf.is_deleted
     *
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    private Byte isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column way_shop_cate_leaf.id
     *
     * @return the value of way_shop_cate_leaf.id
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column way_shop_cate_leaf.id
     *
     * @param id the value for way_shop_cate_leaf.id
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column way_shop_cate_leaf.shop_cate_root_id
     *
     * @return the value of way_shop_cate_leaf.shop_cate_root_id
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    public Integer getShopCateRootId() {
        return shopCateRootId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column way_shop_cate_leaf.shop_cate_root_id
     *
     * @param shopCateRootId the value for way_shop_cate_leaf.shop_cate_root_id
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    public void setShopCateRootId(Integer shopCateRootId) {
        this.shopCateRootId = shopCateRootId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column way_shop_cate_leaf.cate_name
     *
     * @return the value of way_shop_cate_leaf.cate_name
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    public String getCateName() {
        return cateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column way_shop_cate_leaf.cate_name
     *
     * @param cateName the value for way_shop_cate_leaf.cate_name
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    public void setCateName(String cateName) {
        this.cateName = cateName == null ? null : cateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column way_shop_cate_leaf.create_time
     *
     * @return the value of way_shop_cate_leaf.create_time
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column way_shop_cate_leaf.create_time
     *
     * @param createTime the value for way_shop_cate_leaf.create_time
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column way_shop_cate_leaf.update_time
     *
     * @return the value of way_shop_cate_leaf.update_time
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column way_shop_cate_leaf.update_time
     *
     * @param updateTime the value for way_shop_cate_leaf.update_time
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column way_shop_cate_leaf.is_deleted
     *
     * @return the value of way_shop_cate_leaf.is_deleted
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column way_shop_cate_leaf.is_deleted
     *
     * @param isDeleted the value for way_shop_cate_leaf.is_deleted
     * @mbg.generated Fri Apr 06 16:07:59 CST 2018
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}